name: build-and-lint
on:
  push:
    branches: [main, master]
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Install backend deps
        working-directory: server
        run: npm ci

      - name: Lint backend
        working-directory: server
        run: npm run lint -- --max-warnings=0

      - name: Install Frontend deps
        working-directory: client
        run: npm ci

      - name: Lint frontend
        working-directory: client
        run: npm run lint -- --max-warnings=0

      - name: Build backend image
        run: docker build -t backend ./server

      - name: Build frontend image
        run: docker build -t frontend ./client
